# Generated by Django 5.2.6 on 2025-11-26 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banking', '0005_remove_account_email_verification_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_type', models.CharField(choices=[('Mutual_Fund', 'Mutual Fund'), ('Stocks', 'Stocks'), ('Bonds', 'Bonds'), ('Fixed_Deposit', 'Fixed Deposit'), ('SIP', 'Systematic Investment Plan')], help_text='Type of investment', max_length=20)),
                ('investment_name', models.CharField(help_text='Name of the investment (e.g., HDFC Balanced Fund)', max_length=200)),
                ('principal_amount', models.DecimalField(decimal_places=2, help_text='Initial investment amount', max_digits=12)),
                ('current_value', models.DecimalField(decimal_places=2, help_text='Current market value', max_digits=12)),
                ('expected_return_rate', models.DecimalField(decimal_places=2, help_text='Expected annual return rate (%)', max_digits=5)),
                ('investment_status', models.CharField(choices=[('Active', 'Active'), ('Matured', 'Matured'), ('Closed', 'Closed'), ('Pending', 'Pending')], default='Active', help_text='Current investment status', max_length=10)),
                ('start_date', models.DateTimeField(auto_now_add=True, help_text='Investment start date')),
                ('maturity_date', models.DateField(blank=True, help_text='Expected maturity date', null=True)),
                ('risk_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', help_text='Risk level of investment', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('account', models.ForeignKey(help_text='Account from which investment is made', on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='banking.account')),
            ],
            options={
                'verbose_name': 'Investment',
                'verbose_name_plural': 'Investments',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell'), ('Dividend', 'Dividend')], help_text='Type of transaction', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount', max_digits=12)),
                ('units', models.DecimalField(blank=True, decimal_places=4, help_text='Number of units bought/sold', max_digits=12, null=True)),
                ('price_per_unit', models.DecimalField(blank=True, decimal_places=2, help_text='Price per unit', max_digits=12, null=True)),
                ('transaction_date', models.DateTimeField(auto_now_add=True, help_text='Transaction date')),
                ('reference_number', models.CharField(help_text='Transaction reference', max_length=100, unique=True)),
                ('investment', models.ForeignKey(help_text='Associated investment', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='investments.investment')),
            ],
            options={
                'verbose_name': 'Investment Transaction',
                'verbose_name_plural': 'Investment Transactions',
                'ordering': ['-transaction_date'],
            },
        ),
    ]
