# Generated by Django 5.2.8 on 2025-11-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='aadhar_number',
            field=models.CharField(blank=True, help_text='Aadhar Card Number', max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.TextField(blank=True, help_text='Full residential address', null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Date of Birth', null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], help_text='Gender', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='pan_number',
            field=models.CharField(blank=True, help_text='PAN Card Number', max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='account',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=15, null=True, unique=True),
        ),
    ]
