# Generated by Django 5.2.8 on 2025-11-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_account_aadhar_number_account_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='phone_verification_code',
            field=models.CharField(blank=True, help_text='Verification code for phone', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='phone_verification_sent_at',
            field=models.DateTimeField(blank=True, help_text='When verification code was sent', null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='phone_verified',
            field=models.BooleanField(default=False, help_text='Whether phone number is verified'),
        ),
    ]
