# Generated by Django 5.2.8 on 2025-11-23 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_account_phone_verification_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email_verification_token',
            field=models.CharField(blank=True, help_text='Token for email verification', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Whether email is verified via Auth0'),
        ),
    ]
