# Generated by Django 5.2.8 on 2025-11-24 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_account_email_verification_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='email_verification_token',
        ),
        migrations.RemoveField(
            model_name='account',
            name='email_verified',
        ),
    ]
