# Generated by Django 5.2.8 on 2025-11-23 15:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique transaction ID', unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount', max_digits=12)),
                ('transaction_type', models.CharField(choices=[('Deposit', 'Deposit'), ('Transfer', 'Transfer'), ('Withdrawal', 'Withdrawal')], help_text='Type of transaction', max_length=10)),
                ('status', models.CharField(choices=[('Success', 'Success'), ('Failed', 'Failed'), ('Pending', 'Pending')], default='Success', help_text='Transaction status', max_length=10)),
                ('description', models.TextField(blank=True, help_text='Transaction description or note')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Transaction timestamp')),
                ('from_account', models.ForeignKey(blank=True, help_text='Source account (null for deposits)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_transactions', to='banking.account')),
                ('to_account', models.ForeignKey(help_text='Destination account', on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transactions', to='banking.account')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-timestamp'],
            },
        ),
    ]
