# Generated by Django 5.2.8 on 2025-11-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='balance_after',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Account balance after this transaction', max_digits=12, null=True),
        ),
    ]
