# Generated by Django 5.2.8 on 2025-11-23 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_account_aadhar_number_account_address_and_more'),
        ('transactions', '0002_transaction_balance_after'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Account whose ledger this transaction belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions_ledger', to='banking.account'),
        ),
    ]
