# Generated by Django 5.2.8 on 2025-11-24 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0005_remove_account_email_verification_token_and_more'),
        ('transactions', '0003_transaction_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='to_account',
            field=models.ForeignKey(blank=True, help_text='Destination account (null for withdrawals/EMI payments)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transactions', to='banking.account'),
        ),
    ]
