# Generated by Django 5.2.8 on 2025-11-23 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.DecimalField(decimal_places=2, help_text='Requested loan amount', max_digits=12)),
                ('loan_type', models.CharField(choices=[('Personal', 'Personal Loan'), ('Home', 'Home Loan'), ('Auto', 'Auto Loan'), ('Education', 'Education Loan')], help_text='Type of loan', max_length=10)),
                ('loan_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Disbursed', 'Disbursed')], default='Pending', help_text='Current loan status', max_length=10)),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Annual interest rate (%)', max_digits=5)),
                ('tenure_months', models.IntegerField(help_text='Loan tenure in months')),
                ('monthly_emi', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly EMI amount', max_digits=12, null=True)),
                ('purpose', models.TextField(blank=True, help_text='Purpose of the loan')),
                ('application_date', models.DateTimeField(auto_now_add=True, help_text='Date when loan was applied')),
                ('approval_date', models.DateTimeField(blank=True, help_text='Date when loan was approved', null=True)),
                ('account', models.ForeignKey(help_text='Account for which loan is applied', on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='banking.account')),
            ],
            options={
                'verbose_name': 'Loan',
                'verbose_name_plural': 'Loans',
                'ordering': ['-application_date'],
            },
        ),
    ]
