# Generated by Django 5.2.8 on 2025-11-24 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='autopay_enabled',
            field=models.BooleanField(default=False, help_text='Auto-deduct EMI from account balance'),
        ),
        migrations.AddField(
            model_name='loan',
            name='closure_date',
            field=models.DateTimeField(blank=True, help_text='Date when loan was closed', null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='disbursement_date',
            field=models.DateTimeField(blank=True, help_text='Date when loan was disbursed', null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='next_emi_date',
            field=models.DateField(blank=True, help_text='Next EMI due date', null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='remaining_balance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Remaining loan amount to be paid', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Disbursed', 'Disbursed'), ('Closed', 'Closed')], default='Pending', help_text='Current loan status', max_length=10),
        ),
        migrations.CreateModel(
            name='EMIPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emi_number', models.IntegerField(help_text='EMI sequence number (1, 2, 3...)')),
                ('due_date', models.DateField(help_text='EMI due date')),
                ('emi_amount', models.DecimalField(decimal_places=2, help_text='EMI amount', max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount paid', max_digits=12)),
                ('payment_date', models.DateTimeField(blank=True, help_text='Date when EMI was paid', null=True)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Overdue', 'Overdue'), ('Failed', 'Failed')], default='Pending', help_text='Payment status', max_length=10)),
                ('payment_method', models.CharField(blank=True, choices=[('Auto', 'Auto-Pay'), ('Manual', 'Manual Payment'), ('Preclosure', 'Loan Preclosure')], help_text='Payment method', max_length=10, null=True)),
                ('transaction_reference', models.CharField(blank=True, help_text='Transaction reference number', max_length=100, null=True)),
                ('loan', models.ForeignKey(help_text='Associated loan', on_delete=django.db.models.deletion.CASCADE, related_name='emi_payments', to='loans.loan')),
            ],
            options={
                'verbose_name': 'EMI Payment',
                'verbose_name_plural': 'EMI Payments',
                'ordering': ['loan', 'emi_number'],
                'unique_together': {('loan', 'emi_number')},
            },
        ),
    ]
